name: ccs811
description: Driver for AMS CCS811 digital gas sensor
version: 1.0.0
groups:
  - air-quality
  - gas
code_owners:
  - UncleRus
depends:
  - i2cdev
  - log
  - esp_idf_lib_helpers
thread_safe: yes
targets:
  - esp32
  - esp8266
  - esp32s2
  - esp32c3
license: BSD-3
copyrights:
  - name: UncleRus
    year: 2021
  - name: gschorcht
    year: 2017
