name: example
description: An example component
version: 0.0.1
groups:
  - misc
code_owners: trombik
depends:
  # FIXME conditional depends
  - driver
  - log
thread_safe: n/a # yes, no, n/a
targets:
  - esp32
  - esp8266
  - esp32s2
  - esp32c3
license: ISC
copyrights:
  - name: trombik
    year: 2021
