name: Push esp-nn to IDF Component Registry

on:
  push:
    tags:
      - 'v*'

jobs:
  upload_components:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Upload esp-nn to IDF Component Registry
        uses: espressif/upload-components-ci-action@v1
        with:
          name: esp-nn
          namespace: espressif
          version: ${{ github.ref_name }}
          api_token: ${{ secrets.IDF_COMPONENT_API_TOKEN }}
