name: impulse_sensor
description: Driver for impulse output sensors
version: 1.0.0
groups:
  - misc
code_owners: 
  - qb4-dev
depends:
  - i2cdev
  - log
  - esp_idf_lib_helpers
thread_safe: no
targets:
  - esp32
  - esp8266
  - esp32s2
  - esp32c3
license: BSD-3
copyrights:
  - name: qb4-dev
    year: 2024

