name: bme680
description: Driver for BME680 digital environmental sensor
version: 1.0.0
groups:
  - pressure
  - humidity
  - temperature
code_owners:
  - UncleRus
depends:
  - i2cdev
  - log
  - esp_idf_lib_helpers
thread_safe: yes
targets:
  - esp32
  - esp8266
  - esp32s2
  - esp32c3
license: BSD-3
copyrights:
  - name: gschorcht
    year: 2017
  - name: UncleRus
    year: 2019
