name: max1704x
description: Driver for MAX17043/MAX17044/MAX17048/MAX17049 battery fuel gauge
version: 0.9.0
groups:
  - battery
code_owners: shuki25
depends:
  - i2cdev
  - log
  - esp_idf_lib_helpers
thread_safe: yes
targets:
  - esp32
  - esp8266
  - esp32s2
  - esp32c3
license: BSD-3
copyrights:
  - name: shuki25
    year: 2022
