// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: ch10_gui
// https://docs.lvgl.io/8.3/widgets/core/canvas.html?highlight=canvas#example

#include "ui.h"

///////////////////// VARIABLES ////////////////////
lv_obj_t *ui_Screen1;
lv_obj_t *ui_Panel2;
lv_obj_t *ui_canvas;
lv_obj_t *ui_label1;
static lv_color_t *cbuf;

static lv_color_t m_c0 = {.full = 0};
static lv_color_t m_c1 = {.full = 1};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP != 1
#error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////
void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Panel2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel2, 310);
    lv_obj_set_height(ui_Panel2, 230);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_label1 = lv_label_create(ui_Screen1);
    lv_obj_align(ui_label1, LV_ALIGN_TOP_MID, 0, 0);
    lv_label_set_text(ui_label1, "Sine wave model output");

    cbuf = malloc(LV_CANVAS_BUF_SIZE_INDEXED_1BIT(CANVAS_WIDTH, CANVAS_HEIGHT));
    ui_canvas = lv_canvas_create(ui_Screen1);
    lv_canvas_set_buffer(ui_canvas, cbuf, CANVAS_WIDTH, CANVAS_HEIGHT, LV_IMG_CF_INDEXED_1BIT);
    lv_canvas_set_palette(ui_canvas, 0, lv_color_white());
    lv_canvas_set_palette(ui_canvas, 1, lv_color_black());
    lv_canvas_fill_bg(ui_canvas, m_c0, LV_OPA_COVER);
    lv_obj_center(ui_canvas);
}

void ui_init(void)
{
    lv_disp_t *dispp = lv_disp_get_default();
    lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                              false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    lv_disp_load_scr(ui_Screen1);
}

void ui_setPoint(lv_coord_t x_pos, lv_coord_t y_pos)
{
    for (int y = y_pos; y < y_pos + 5; y++)
    {
        for (int x = x_pos; x < x_pos + 5; x++)
        {
            lv_canvas_set_px_color(ui_canvas, x, y, m_c1);
        }
    }
}
