# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: custom_cloud_config.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x63ustom_cloud_config.proto\x12\x05\x63loud\"5\n\x10\x43mdGetSetDetails\x12\x0e\n\x06UserID\x18\x01 \x01(\t\x12\x11\n\tSecretKey\x18\x02 \x01(\t\"S\n\x11RespGetSetDetails\x12(\n\x06Status\x18\x01 \x01(\x0e\x32\x18.cloud.CloudConfigStatus\x12\x14\n\x0c\x44\x65viceSecret\x18\x02 \x01(\t\"\xb9\x01\n\x12\x43loudConfigPayload\x12&\n\x03msg\x18\x01 \x01(\x0e\x32\x19.cloud.CloudConfigMsgType\x12\x36\n\x13\x63md_get_set_details\x18\n \x01(\x0b\x32\x17.cloud.CmdGetSetDetailsH\x00\x12\x38\n\x14resp_get_set_details\x18\x0b \x01(\x0b\x32\x18.cloud.RespGetSetDetailsH\x00\x42\t\n\x07payload*D\n\x11\x43loudConfigStatus\x12\x0b\n\x07Success\x10\x00\x12\x10\n\x0cInvalidParam\x10\x01\x12\x10\n\x0cInvalidState\x10\x02*I\n\x12\x43loudConfigMsgType\x12\x18\n\x14TypeCmdGetSetDetails\x10\x00\x12\x19\n\x15TypeRespGetSetDetails\x10\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'custom_cloud_config_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CLOUDCONFIGSTATUS._serialized_start=364
  _CLOUDCONFIGSTATUS._serialized_end=432
  _CLOUDCONFIGMSGTYPE._serialized_start=434
  _CLOUDCONFIGMSGTYPE._serialized_end=507
  _CMDGETSETDETAILS._serialized_start=36
  _CMDGETSETDETAILS._serialized_end=89
  _RESPGETSETDETAILS._serialized_start=91
  _RESPGETSETDETAILS._serialized_end=174
  _CLOUDCONFIGPAYLOAD._serialized_start=177
  _CLOUDCONFIGPAYLOAD._serialized_end=362
# @@protoc_insertion_point(module_scope)
