name: pcf8563
description: Driver for PCF8563 (BM8563) real-time clock/calendar
version: 1.0.0
groups:
  - rtc
code_owners: UncleRus
depends:
  - i2cdev
  - log
  - esp_idf_lib_helpers
thread_safe: yes
targets:
  - esp32
  - esp8266
  - esp32s2
  - esp32c3
license: BSD-3
copyrights:
  - name: UncleRus
    year: 2020
