name: rda5807m
description: Driver for single-chip broadcast FM radio tuner RDA5807M
version: 1.0.0
groups:
  - misc
code_owners: UncleRus
depends:
  - i2cdev
  - log
  - esp_idf_lib_helpers
thread_safe: yes
targets:
  - esp32
  - esp8266
  - esp32s2
  - esp32c3
license: BSD-3
copyrights:
  - name: UncleRus
    year: 2018
