name: aht
description: Driver for AHT10/AHT15/AHT20 temperature and humidity sensor
version: 1.0.0
groups:
  - temperature
  - humidity
code_owners:
  - UncleRus
depends:
  - i2cdev
  - log
  - esp_idf_lib_helpers
thread_safe: yes
targets:
  - esp32
  - esp8266
  - esp32s2
  - esp32c3
license: BSD-3
copyrights:
  - name: UncleRus
    year: 2021
