name: mhz19b
description: Driver for MH-Z19B NDIR CO₂ sensor
version: 1.1.0
groups:
  - air-quality
  - gas
code_owners:
  - Erriez
  - DavidD
depends:
  - log
  - esp_idf_lib_helpers
thread_safe: no
targets:
  - esp32
  - esp8266
  - esp32s2
  - esp32c3
license: BSD-3
copyrights:
  - name: Erriez
    year: 2020
  - name: DavidD
    year: 2021
