clean_set:
  paths:
    - "./data/clean_set/hiesp"
    - "./data/clean_set/hilexin"
  normalization: True
  target_dB: -36
noise_set:
  paths:
    - "./data/noise_set/silence"
    - "./data/noise_set/pink"
    - "./data/noise_set/pub"
  normalization: True
  target_dB: -36
output_set:
  path: "./data/output_set"
  remove_old_files: true
  snr:
    - snr_dB: 10
      clean_gain_dB: 0
    - snr_dB: 5
      clean_gain_dB: 0
    - snr_dB: 0
      clean_gain_dB: 5
player:
  play_output: true