name: max7219
description: Driver for 8-Digit LED display drivers, MAX7219/MAX7221
version: 1.0.0
groups:
  - led
code_owners: UncleRus
depends:
  - driver
  - log
thread_safe: yes
targets:
  - esp32
  - esp32s2
  - esp32c3
license: BSD-3
copyrights:
  - name: UncleRus
    year: 2019
