name: calibration
description: Multi-point calibration library
version: 0.1.0
groups:
  - common
code_owners:
  - UncleRus
depends:
  - log
thread_safe: n/a
targets:
  - esp32
  - esp8266
  - esp32s2
  - esp32c3
license: BSD-3
copyrights:
  - name: UncleRus
    year: 2023
