// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.2.0
// Project name: ch9_gui

#ifndef _CH9_GUI_UI_H
#define _CH9_GUI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_txtTime;
extern lv_obj_t * ui_pnlLight;
extern lv_obj_t * ui_txtLight;
extern lv_obj_t * ui_lblLight;
extern lv_obj_t * ui_pnlTemp;
extern lv_obj_t * ui_txtTemp;
extern lv_obj_t * ui_lblTemp;
void ui_event_chkConnected(lv_event_t * e);
extern lv_obj_t * ui_chkConnected;
extern lv_obj_t * ui____initial_actions0;






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
