name: bh1750
description: Driver for BH1750 light sensor
version: 1.1.0
groups:
  - light
code_owners:
  - UncleRus
depends:
  - i2cdev
  - log
  - esp_idf_lib_helpers
thread_safe: yes
targets:
  - esp32
  - esp8266
  - esp32s2
  - esp32c3
license: BSD-3
copyrights:
  - name: UncleRus
    year: 2018
  - name: Andrej
    year: 2017
