name: mcp23008
description: Driver for 8-bit I2C GPIO expander MCP23008
version: 1.0.0
groups:
  - gpio
code_owners: UncleRus
depends:
  - i2cdev
  - log
  - esp_idf_lib_helpers
thread_safe: yes
targets:
  - esp32
  - esp8266
  - esp32s2
  - esp32c3
license: BSD-3
copyrights:
  - name: UncleRus
    year: 2018
