:unity:
  :when_no_prototypes: :warn
  :enforce_strict_ordering: TRUE
  :treat_as:
    uint8:    HEX8
    uint16:   HEX16
    uint32:   UINT32
    int8:     INT8
    bool:     UINT8
  :treat_externs: :exclude
  :weak: __attribute__((weak))
  :treat_externs: :include
